name: Test with GCC

on:
  push:
    branches:
      - matrix-test
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dependencies: [openmpi, mpich, fmt]
        
    steps:
      - name: Test
        run: echo ${{ matrix.dependencies }}
