name: Test with GCC

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dependencies: [openmpi, mpich, fmt]
        
    steps:
      - name: Test
        run: |
          echo "From action ${{ matrix.dependencies }}"
          chmod +x ../scripts/install_gcc.sh
          ../scripts/install_gcc.sh
