name: Test with GCC

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dependencies: [openmpi, mpich, fmt]
        
    steps:
      - name: Test
        run: |
          echo "From action ${{ matrix.dependencies }}"
          echo "${{ github.workspace }}"
          ls ..
          #ls ${{ github.workspace }}
          #chmod +x ./install_gcc.sh
          #./install_gcc.sh ${{ matrix.dependencies }}
