name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
   

    steps:
      - name: Cache
        uses: actions/cache@v1.1.2
        id: id_save_dir
        with:
          # A directory to store and save the cache
          path: save_dir
          # An explicit key for restoring and saving the cache
          key: key_save_dir
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          #restore-keys: #optional

      - name: Generte Cache
        if: steps.id_save_dir.outputs.cache-hit != 'true'
        run: |
          echo kein Cache hit!
          mkdir save_dir
          touch test.txt
      - name: Run a multi-line script
        run:  echo Cache hit!

