 
name: Boost_Matrix

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        boost: [1_72_0, 1_71_0, 1_70_0, 1_69_0, 1_68_0, 1_67_0]
       
    steps:
      - name: Cache
        uses: actions/cache@v1.1.2
        id: check-cache
        with:
          # A directory to store and save the cache
          path: boost_dir 
          # An explicit key for restoring and saving the cache
          key: boost-${{ matrix.boost }}
 
       
      - name: Build Boost ${{ matrix.boost }}
        #if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          echo installing Boost ${{ matrix.boost }}
          rm -rf boost_dir
          mkdir boost_dir
          cd boost_dir
          wget  https://dl.bintray.com/boostorg/release/$(tr '_' '.' <<<"${{ matrix.boost }}")/source/boost_${{ matrix.boost }}.tar.gz
          tar -zxf boost_${{ matrix.boost }}.tar.gz
          cd boost_${{ matrix.boost }}
          ./bootstrap.sh --prefix=boost_dir --with-toolset=gcc
          ./b2 -j4 --with-atomic --with-filesystem --with-program_options --with-regex --with-system --with-chrono --with-date_time --with-thread
          ./b2 install

      - name: Generte Cache
        #if: steps.boost.outputs.cache-hit != 'true'
        run: |
          ls boost_dir

      - name: ls
        run: ls
       
